<?php

declare(strict_types=1);

namespace TheCodingMachine\GraphQLite;

use GraphQL\Type\Definition\InputObjectType;
use Psr\Container\ContainerInterface;
use ReflectionClass;
use ReflectionFunctionAbstract;
use ReflectionMethod;
use TheCodingMachine\GraphQLite\Directives\DirectiveRegistry;
use TheCodingMachine\GraphQLite\Middlewares\InputObjectTypeHandlerInterface;
use TheCodingMachine\GraphQLite\Middlewares\InputObjectTypeMiddlewareInterface;
use TheCodingMachine\GraphQLite\Reflection\DocBlock\DocBlockFactory;
use TheCodingMachine\GraphQLite\Types\InputType;
use TheCodingMachine\GraphQLite\Types\InputTypeValidatorInterface;
use TheCodingMachine\GraphQLite\Types\MutableInputObjectType;
use TheCodingMachine\GraphQLite\Types\ResolvableMutableInputInterface;
use TheCodingMachine\GraphQLite\Types\ResolvableMutableInputObjectType;
use TheCodingMachine\GraphQLite\Utils\DescriptionResolver;

use function array_shift;
use function assert;
use function is_callable;

/**
 * This class is in charge of creating Webonyx InputTypes from Factory annotations.
 */
class InputTypeGenerator
{
    /** @var array<string, ResolvableMutableInputObjectType> */
    private array $factoryCache = [];
    /** @var array<string, InputType> */
    private array $inputCache = [];

    public function __construct(
        private InputTypeUtils $inputTypeUtils,
        private FieldsBuilder $fieldsBuilder,
        private InputTypeValidatorInterface|null $inputTypeValidator = null,
        private AnnotationReader|null $annotationReader = null,
        private DocBlockFactory|null $docBlockFactory = null,
        private DescriptionResolver $descriptionResolver = new DescriptionResolver(true),
        private InputObjectTypeMiddlewareInterface|null $inputObjectTypeMiddleware = null,
        private DirectiveRegistry|null $directiveRegistry = null,
    ) {
    }

    public function mapFactoryMethod(string $factory, string $methodName, ContainerInterface $container): ResolvableMutableInputObjectType
    {
        $method = new ReflectionMethod($factory, $methodName);

        if ($method->isStatic()) {
            $object = $factory;
        } else {
            $object = $container->get($factory);
        }

        [$inputName, $className] = $this->inputTypeUtils->getInputTypeNameAndClassName($method);

        if (! isset($this->factoryCache[$inputName])) {
            $type = new ResolvableMutableInputObjectType(
                $inputName,
                $this->fieldsBuilder,
                $object,
                $methodName,
                $this->resolveFactoryDescription($method),
                $this->canBeInstantiatedWithoutParameter($method, false),
            );

            /** @var class-string $factoryClass */
            $factoryClass = $factory;
            $decorated = $this->runInputObjectMiddleware(new ReflectionClass($factoryClass), $type);
            assert($decorated instanceof ResolvableMutableInputObjectType);
            $this->factoryCache[$inputName] = $decorated;
        }

        return $this->factoryCache[$inputName];
    }

    /**
     * Resolves the description for an input type produced by a #[Factory]-annotated method,
     * combining an explicit {@see Factory::$description} with an optional docblock fallback
     * according to the configured {@see DescriptionResolver}.
     *
     * Replaces the long-standing `// TODO: add comment argument.` gap — input types generated by
     * factories now participate in the same description resolution pipeline as every other
     * schema element.
     */
    private function resolveFactoryDescription(ReflectionMethod $method): string|null
    {
        if ($this->annotationReader === null) {
            return null;
        }

        $factoryAnnotation = $this->annotationReader->getFactoryAnnotation($method);
        $explicit = $factoryAnnotation?->getDescription();

        $docblockDerived = null;
        if ($this->docBlockFactory !== null && $this->descriptionResolver->isDocblockFallbackEnabled()) {
            $summary = $this->docBlockFactory->create($method)->getSummary();
            $docblockDerived = $summary === '' ? null : $summary;
        }

        return $this->descriptionResolver->resolve($explicit, $docblockDerived);
    }

    /** @param class-string<object> $className */
    public function mapInput(string $className, string $inputName, string|null $description, bool $isUpdate): InputType
    {
        if (! isset($this->inputCache[$inputName])) {
            $type = new InputType(
                $className,
                $inputName,
                $description,
                $isUpdate,
                $this->fieldsBuilder,
                $this->inputTypeValidator,
            );

            $decorated = $this->runInputObjectMiddleware(new ReflectionClass($className), $type);
            assert($decorated instanceof InputType);
            $this->inputCache[$inputName] = $decorated;
        }

        return $this->inputCache[$inputName];
    }

    /** @param ReflectionClass<object> $refClass */
    private function runInputObjectMiddleware(ReflectionClass $refClass, MutableInputObjectType $type): MutableInputObjectType
    {
        if ($this->inputObjectTypeMiddleware === null || $this->directiveRegistry === null) {
            return $type;
        }

        $directives = $this->directiveRegistry->inputObjectTypeDirectives($refClass);
        if ($directives === []) {
            return $type;
        }

        $descriptor = new InputObjectTypeDescriptor($refClass, $type, $directives);

        return $this->inputObjectTypeMiddleware->process(
            $descriptor,
            new class implements InputObjectTypeHandlerInterface {
                public function handle(InputObjectTypeDescriptor $descriptor): MutableInputObjectType
                {
                    return $descriptor->getType();
                }
            },
        );
    }

    public static function canBeInstantiatedWithoutParameter(ReflectionFunctionAbstract $refMethod, bool $skipFirstArgument): bool
    {
        $nbParams = $refMethod->getNumberOfRequiredParameters();
        if (($nbParams === 0 && $skipFirstArgument === false) || ($nbParams <= 1 && $skipFirstArgument === true)) {
            return true;
        }

        $parameters = $refMethod->getParameters();

        if ($skipFirstArgument) {
            array_shift($parameters);
        }

        // Let's scan all the parameters. They must either have a default value or be nullable.
        foreach ($parameters as $parameter) {
            if (! $parameter->isDefaultValueAvailable() && ! $parameter->allowsNull()) {
                return false;
            }
        }

        return true;
    }

    /** @param ResolvableMutableInputInterface&InputObjectType $inputType */
    public function decorateInputType(string $className, string $methodName, ResolvableMutableInputInterface $inputType, ContainerInterface $container): void
    {
        $method = new ReflectionMethod($className, $methodName);

        if ($method->isStatic()) {
            $object = $className;
        } else {
            $object = $container->get($className);
        }

        $callable = [$object, $methodName];
        assert(is_callable($callable));
        $inputType->decorate($callable);
    }
}
